### ISSUE TITLE
Instance or pod-level storage provisioning

### ISSUE THREAD

**Issue by brainstorm** [hsanjuan/ansible-ipfs-cluster#1]
Hi @hsanjuan, thanks so much for publishing this! It's what I had in mind when I started with my own recipes a few weeks ago 👍 

Now, my biggest doubt right now and major blocker after setting up my own kubernetes-ipfs cluster is: how do you guys manage **LOCAL** (instance/VM-level) disk space dynamically? I've seen [related issues](https://github.com/ipfs/ipfs-cluster/issues/49) which makes me think it's been worked on, but it's still a bit of a mystery for me :-S

I have some ideas but don't want to reinvent the wheel... can you point me to any issue/debate on this area to have a notion on which direction is this going to be solved in practice?

**Comment by hsanjuan** [comment]
We don't do any storage management @brainstorm. You are going to have to invent the wheel here.

Kubernetes-ipfs is so far used for ephemeral testing, all storage is local, everything is created on the test and wiped once the containers are destroyed. The issue you link is about how ipfs-cluster can decide where to pin stuff, and using a disk-free metric is one option. It's not really related to managing dynamic storage for docker/kubernetes clusters. Sorry I didn't answer before to the messages where you asked this, but I have very little experience on how that would be done.

**Comment by brainstorm** [comment]
Oh, no worries and thanks so much for the explanation!

I guess that for testing purposes, ephemeral just works, given that the default replication factor is >=2, although not sure how that would pan out in production environments :-S

@ohofmann
