### ISSUE TITLE
ipfs_use_badger is undefined

### ISSUE THREAD

**Issue by qwzhou89** [hsanjuan/ansible-ipfs-cluster#8]
when i use it to install the go-ipfs and ipfs-cluster,the follow error occured.

TASK [ipfs : copy default config] **********************************************
fatal: [jc-swtc-ipfs-1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ipfs_use_badger' is undefined"}

**Comment by hsanjuan** [comment]
try defining that variable in group vars.
